name: cavsim-dev
channels:
- conda-forge
- defaults
platforms:
- win-64
- linux-64
dependencies:
- python
- pytest
- invoke
- cmake
- ninja
- pybind11
environment:
  PYTHONPATH:
    - {{root}}/src/python
    - {{root}}/artifacts
